name: "Build and Deploy"
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout / Clone repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        # submodules: true
        # If using the 'assets' git submodule from Chirpy Starter, uncomment above
        # (See: https://github.com/cotes2020/chirpy-starter/tree/main/assets)

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3   # reads from a '.ruby-version' or '.tools-version' file if 'ruby-version' is omitted
        bundler-cache: true

    - name: Cache Gemfiles
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Build with Jekyll
      run: bundle exec jekyll build
      env:
        JEKYLL_ENV: "production"
    
    - name: Test site
      run: |
        bundle exec htmlproofer _site --disable-external --check-html --allow_hash_href

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rzv --delete --delete-excluded --chmod=g+rwx"
        SOURCE: "/home/runner/work/chase-blog/chase-blog/_site"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}

      # - name: Purge CDN / Cloudflare
    #   name: Purge Cloudflare Cache
    #   uses: jakejarvis/cloudflare-purge-action@v0.3.0
    #   env:
    #     CLOUDFLARE_ZONE: $
    #     CLOUDFLARE_TOKEN: $
